-- ============================================================
-- Alina Body — таблицы, которых нет в новой course_*-схеме,
-- но которые всё ещё нужны фронтенду (tracker, waitlist).
-- Остальной backend мигрирован на course_* (см. api/*.js).
-- ============================================================

create table if not exists public.tracker (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  program_id text not null,            -- UUID курса (course_id)
  day_number integer,
  mood text,
  energy integer,
  note text,
  logged_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  program_slug text not null default 'challenge-21',
  created_at timestamptz not null default now()
);

create index if not exists idx_tracker_user_program on public.tracker (user_id, program_id);
create index if not exists idx_waitlist_email on public.waitlist (email);
